backend:
  name: git-gateway
  branch: develop

media_folder: static/assets
public_folder: /assets

collections:
  - name: settings
    label: Настройки
    files:
      - label: Сайт
        name: site
        file: content/static/site.yml
        fields:
          - { name: title, label: Название сайта }
          - { name: copyright, label: Копирайт }
          - { name: postsEnabled, label: Включить новости, widget: boolean }
  - name: pages
    label: Страницы
    files:
      - name: main
        label: Главная
        file: content/static/main.yml
        fields:
          - name: hero
            label: Hero
            widget: object
            fields:
              - { name: title, label: Заголовок }
              - { name: subtitle, label: Подзаголовок }
              - { name: image, label: Изображение, widget: image }
              - { name: button, label: Кнопка заказа }
          - name: about
            label: О нас
            widget: object
            fields:
              - { name: title, label: Заголовок }
              - { name: text, label: Текст }
          - name: pros
            label: Преимущества
            widget: object
            fields:
              - { name: title, label: Заголовок }
              - { name: list, label: Список }
          - name: cta
            label: Призыв к действию
            widget: object
            fields:
              - { name: text, label: Текст }
              - { name: button, label: Кнопка заказа }
          - name: posts
            label: Новости
            widget: object
            fields:
              - { name: title, label: Заголовок }
      - name: about
        label: О компании
        file: content/static/about.yml
        fields:
          - { name: title, label: Заголовок }
          - name: body
            label: Текст
            widget: markdown
      - name: contacts
        label: Контакты
        file: content/static/contacts.yml
        fields:
          - { name: companyName, label: Название компании }
          - { name: address, label: Адрес }
          - { name: email, label: Email }
          - name: phoneNumbers
            label: Телефонные номера
            widget: list
            field:
              { name: number, label: Номер, widget: string }
          - name: map
            label: Карта
            widget: object
            fields:
              - name: lat
                label: Широта
                widget: number
                valueType: float
              - name: long
                label: Долгота
                widget: number
                valueType: float
              - name: zoom
                label: Масштаб
                widget: number
                valueType: float
  - name: news
    label: Новости
    folder: content/news
    fields:
      - { name: date, label: Дата, widget: date }
      - { name: title, label: Заголовок }
      - { name: body, label: Текст, widget: markdown }
  - name: services
    label: Услуги
    folder: content/services
    fields:
      - { name: slug, label: Name }
      - { name: title, label: Заголовок }
      - { name: description, label: Описание, widget: markdown }
      - { name: steps, label: Схема работы, widget: list }
      - { name: includes, label: Услуга включает, widget: list }