backend:
  name: git-gateway
  branch: develop

media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: Страницы
    delete: false
    files:
      - name: main
        label: Главная
        file: content/pages/main.yml
        fields:
          - name: hero
            label: Hero
            widget: object
            fields:
              - { name: title, label: Заголовок }
              - { name: subtitle, label: Подзаголовок }
              - { name: image, label: Изображение, widget: image }
              - { name: button, label: Кнопка заказа }
          - name: about
            label: О нас
            widget: object
            fields:
              - { name: title, label: Заголовок }
              - { name: text, label: Текст }
          - name: pros
            label: Преимущества
            widget: object
            fields:
              - { name: title, label: Заголовок }
              - { name: list, label: Список, widget: list }
              - { name: image, label: Изображение, widget: image }
          - name: cta
            label: Призыв к действию
            widget: object
            fields:
              - { name: title, label: Заголовок }
              - { name: text, label: Текст }
              - { name: button, label: Кнопка заказа }
          - name: posts
            label: Новости
            widget: object
            fields:
              - { name: title, label: Заголовок }
      - name: about
        label: О компании
        file: content/pages/about.yml
        fields:
          - { name: title, label: Заголовок }
          - { name: image, label: Изображение, widget: image }
          - name: body
            label: Текст
            widget: markdown
      - name: contacts
        label: Контакты
        file: content/pages/contacts.yml
        fields:
          - { name: companyName, label: Название компании }
          - { name: address, label: Адрес }
          - { name: email, label: Email }
          - name: phoneNumbers
            label: Телефонные номера
            widget: list
          - name: map
            label: Карта
            widget: object
            fields:
              - name: lat
                label: Широта
                widget: number
                valueType: float
              - name: long
                label: Долгота
                widget: number
                valueType: float
              - name: zoom
                label: Масштаб
                widget: number
                valueType: float
  # - name: news
  #   label: Новости
  #   folder: content/news
  #   fields:
  #     - { name: date, label: Дата, widget: date }
  #     - { name: title, label: Заголовок }
  #     - { name: body, label: Текст, widget: markdown }
  - name: services
    label: Услуги
    folder: content/services
    create: true
    fields:
      - name: slug
        label: Url
        pattern:
          - "[a-z0-9-_]{5, }"
          - "Url должен быть минимум 5 символов длинной и содержать только следующие символы: a-z 0-9 - _"
      - { name: title, label: Заголовок }
      - { name: icon, label: Иконка }
      - { name: shortDescription, label: Краткое описание }
      - { name: image, label: Изображение, widget: image }
      - { name: description, label: Описание, widget: markdown }
      - { name: steps, label: Схема работы, widget: list }
      - name: additional
        label: Дополнительно
        widget: object
        fields:
          - { name: title, label: Заголовок }
          - { name: text, label: Текст, widget: markdown }
          - { name: image, label: Изображение, widget: image }
      - name: cta
        label: Призыв к действию
        widget: object
        fields:
          - { name: title, label: Заголовок }
          - { name: text, label: Текст }
          - { name: button, label: Кнопка }